### ISSUE TITLE
Not working as of 24/06/15

### ISSUE THREAD

**Issue by phixion** [fdahms/facebook_timeline_cleaner#1]
its just scrolling and scrolling and deletes nothing. Also the button only pops up on the timeline review not on the activity log. Can you please fix it?

THX

**Comment by sanerdk** [comment]
Same problem here

**Comment by phixion** [comment]
I tried different browsers by the way (chrome and ff) same results

**Comment by fdahms** [comment]
Do you remove the dryrun checkbox?

**Comment by fdahms** [comment]
Look here for screenshots: 
https://greasyfork.org/de/scripts/9106-facebook-timeline-cleaner

**Comment by phixion** [comment]
yeah removed it

**Comment by phixion** [comment]
http://i.imgur.com/wZMuHl8.png could it be this?
this is how it looks for me after a minute: http://i.imgur.com/4W31mBj.png

**Comment by fdahms** [comment]
try it now :)

**Comment by phixion** [comment]
seems to run now;

edit:jep definitely working now! THX for the fix

**Comment by sanerdk** [comment]
Works right now, thank you for script. We could have a auto group poster etc. :)
